---
title: 'COVID-19 no Brasil: Número de Reprodução Instantâneo.'
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source code: embed
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(EpiEstim)
library(ggplot2)
library(dplyr)
library(readxl)
library(utils)
library(httr)
library(tidyverse)
library(RCurl)

##########################################################################
###  Programa para estimar Número Básico de Repodrução Instantâneo     ###
###  https://cran.r-project.org/web/packages/EpiEstim/EpiEstim.pdf     ###
### by. Alex Rodrigues                                                 ###
##########################################################################

Sys.setlocale("LC_TIME", "Portuguese")

base.mun <- read.csv(text = getURL("https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-cities-time.csv"))
base.mun$state <- as.character(base.mun$state)
base.mun$date <- as.Date(base.mun$date)
base.mun$state <- ifelse(base.mun$state == "TOTAL", "BRASIL", base.mun$state)
base.mun <- base.mun %>% filter(date!=max(date))


base <- base.mun %>% select(date, state, totalCases, newCases, deaths, newDeaths) %>% 
  group_by(date, state) %>% summarise_all(list(sum)) %>% 
  mutate(CFR.obs = deaths/totalCases)

#correcao casos
Vtb.UF <- readRDS(file="data/Vtb.UF.RDS")


#correção número de casos
CFR.KS.bb <-0.01635
lag.days <- 12
base.correct <- base %>% left_join(Vtb.UF,by="state" ) %>% filter(deaths>15) %>%
                      mutate(totalCases.est = deaths/(VTB*CFR.KS.bb),date.cases = date-lag.days) %>%  
                      arrange(state,date.cases)%>%group_by(state) %>%
                      mutate(newCases.est=totalCases.est-lag(totalCases.est)) %>%
                      select(date.cases,state,totalCases.est,newCases.est,VTB)
base <- base %>% left_join(base.correct, by=c("date"="date.cases","state"="state"))



states.100casos <- base %>% group_by(state) %>%  filter(totalCases>100) %>% count(state) %>% filter(n>5)
base.100casos <- base %>% group_by(state) %>%  filter(totalCases>100 & state %in% states.100casos$state)
nmax <- max(states.100casos$n)

#janela rolante de 5 e 10 dias
resu5 <- list()
resu15<- list()
R0 <- list()

for(i in 1:nrow(states.100casos)){
     
  #print(states.100casos$state[i])
  base.state <-base.100casos %>% filter(state==states.100casos$state[i]) %>% arrange(date) %>% mutate(newCases=abs(newCases))
     
  if(nrow(base.state)>16){    
    for(j in c(5,15)){
        
        TT <-  nrow(base.state)
        t_start <- seq(2, TT-j)
        t_end <- t_start + j 
        
        ress <- estimate_R( base.state$newCases, 
                                 method="parametric_si",
                                 config = make_config(list(
                                   t_start = t_start,
                                   t_end = t_end,
                                   mean_si = 4.7, 
                                   std_si = 2.9))
                             )
        if(j==5){
          resu5[[i]] <- data.frame(date=base.state$date[t_start],IC.i.5=ress$R$`Quantile.0.025(R)`,Est.5=ress$R$`Mean(R)`,IC.s.5=ress$R$`Quantile.0.975(R)`)
          names(resu5)[i] <- states.100casos$state[i]
        }
        if(j==15){
          resu15[[i]] <- data.frame(date=base.state$date[t_start],IC.i.15=ress$R$`Quantile.0.025(R)`,Est.15=ress$R$`Mean(R)`,IC.s.15=ress$R$`Quantile.0.975(R)`)
          names(resu15)[i] <- states.100casos$state[i]
        }
      }
      
      
  }else{
    j=5
    TT <-  nrow(base.state)
    t_start <- seq(2, TT-j)
    t_end <- t_start + j 
    
    ress <- estimate_R( base.state$newCases, 
                        method="parametric_si",
                        config = make_config(list(
                          t_start = t_start,
                          t_end = t_end,
                          mean_si = 4.7, 
                          std_si = 2.9))
                        )
    resu5[[i]] <- data.frame(date=base.state$date[t_start],IC.i.5=ress$R$`Quantile.0.025(R)`,Est.5=ress$R$`Mean(R)`,IC.s.5=ress$R$`Quantile.0.975(R)`)
    names(resu5)[i] <- states.100casos$state[i]
  }
  
    
        t_start <- 2
        t_end <- nrow(base.state)
        
    res.0 <- estimate_R( base.state$newCases, 
                                 method="parametric_si",
                                 config = make_config(list(
                                   t_start = t_start,
                                   t_end = t_end,
                                   mean_si = 4.7, 
                                   std_si = 2.9))
                             )
  
  R0[[i]] <- data.frame(date=base.state$date[t_start],IC.i.r0= res.0$R$`Quantile.0.025(R)`,Est.r0= res.0$R$`Mean(R)`,IC.s.r0= res.0$R$`Quantile.0.975(R)`)
    names(R0)[i] <- states.100casos$state[i]
  
}



states.100casos.est <- base %>% filter(!is.na(newCases.est)) %>% group_by(state) %>%  filter(totalCases.est>100) %>% count(state)  %>% filter(n>5)
base.100casos.est <- base %>% group_by(state) %>%  filter(totalCases.est>100 & state %in% states.100casos.est$state) %>% filter(!is.na(newCases.est))
nmax <- max(states.100casos$n)

#janela rolante de 5 e 10 dias
resu5.est <- list()
resu15.est<- list()
R0.est <- list()

for(i in 1:nrow(states.100casos.est)){
     
  #print(states.100casos.est$state[i])
  base.state <-base.100casos.est %>% filter(state==states.100casos.est$state[i]) %>% arrange(date) %>% mutate(newCases.est=abs(newCases.est))
     
  if(nrow(base.state)>16){    
    for(j in c(5,15)){
        
        TT <-  nrow(base.state)
        t_start <- seq(2, TT-j)
        t_end <- t_start + j 
        
        ress <- estimate_R( base.state$newCases.est, 
                                 method="parametric_si",
                                 config = make_config(list(
                                   t_start = t_start,
                                   t_end = t_end,
                                   mean_si = 4.7, 
                                   std_si = 2.9))
                             )
        if(j==5){
          resu5.est[[i]] <- data.frame(date=base.state$date[t_start],IC.i.5=ress$R$`Quantile.0.025(R)`,Est.5=ress$R$`Mean(R)`,IC.s.5=ress$R$`Quantile.0.975(R)`)
          names(resu5.est)[i] <- states.100casos.est$state[i]
        }
        if(j==15){
          resu15.est[[i]] <- data.frame(date=base.state$date[t_start],IC.i.15=ress$R$`Quantile.0.025(R)`,Est.15=ress$R$`Mean(R)`,IC.s.15=ress$R$`Quantile.0.975(R)`)
          names(resu15.est)[i] <- states.100casos.est$state[i]
        }
      }
      
      
  }else{
    j=5
    TT <-  nrow(base.state)
    t_start <- seq(2, TT-j)
    t_end <- t_start + j 
    
    ress <- estimate_R( base.state$newCases.est, 
                        method="parametric_si",
                        config = make_config(list(
                          t_start = t_start,
                          t_end = t_end,
                          mean_si = 4.7, 
                          std_si = 2.9))
                        )
    resu5.est[[i]] <- data.frame(date=base.state$date[t_start],IC.i.5=ress$R$`Quantile.0.025(R)`,Est.5=ress$R$`Mean(R)`,IC.s.5=ress$R$`Quantile.0.975(R)`)
    names(resu5.est)[i] <- states.100casos.est$state[i]
  }
  
    
        t_start <- 2
        t_end <- nrow(base.state)
        
    res.0 <- estimate_R( base.state$newCases.est, 
                                 method="parametric_si",
                                 config = make_config(list(
                                   t_start = t_start,
                                   t_end = t_end,
                                   mean_si = 4.7, 
                                   std_si = 2.9))
                             )
  
  R0.est[[i]] <- data.frame(date=base.state$date[t_start],IC.i.r0= res.0$R$`Quantile.0.025(R)`,Est.r0= res.0$R$`Mean(R)`,IC.s.r0= res.0$R$`Quantile.0.975(R)`)
    names(R0.est)[i] <- states.100casos.est$state[i]
  
}

```


Column {data-width=225}
-----------------------------------------------------------------------

### Parâmetros

```{r , echo = FALSE }

selectInput(inputId = "onde", label = "UF a ser analisada:", 
                       choices = sort(unique(states.100casos$state)), selected = "BRASIL", multiple = FALSE)

checkboxInput("checkbox", label = "Com correção para subnotificação", value = FALSE)
```

### Estimativa R0

```{r , echo = FALSE }
tableOutput("table.R0")

```

### Nota

Esta sessão apresenta a estimativa de $R_t$, número esperado de casos secundários decorrentes de um caso primário infectado no momento $t$, por Unidade da Federação do Brasil, bem como estimativa do número básico de reprodução $R_0$. Utilizou-se uma abordagem Bayesiana com método de regressão de Poisson com priori Gamma para geração do tempo e janelas rolantes de 5 e 15 dias. Para mais detalhes, ver Cori et al. (2013).

Aplicou-se uma correção para subnotificações baseada no estudo de Lachmann, A. (2020). Trata-se da estimação do número acumulado de casos exclusivamente a partir do número acumulado de mortes, utilizando como referência um país que comprovadamente apresentou uma boa capacidade de testagem. A Coréia do Sul foi utilizada como referência neste caso. 


*Referências*:

- Cori, A., Ferguson, N. M., Fraser, C., & Cauchemez, S. (2013). A new framework and software to estimate time-varying reproduction numbers during epidemics. American journal of epidemiology, 178(9), 1505-1512.

- Lachmann, A. (2020). Correcting under-reported COVID-19 case numbers. medRxiv.



```{r , echo = FALSE }
 Rt.state <- reactive({
         
         
    if(input$checkbox){
        state.existe <- names(resu15.est)[!(sapply(resu15.est,is.null))]
        validate(
      need((input$onde %in% state.existe), "O estado escolhido não possui amostra suficiente.")
           )
        Rt.state <- resu5.est[[input$onde]] %>% left_join(resu15.est[[input$onde]],by="date") 
      }else{
         state.existe <- names(resu15)[!(sapply(resu15,is.null))]
          validate(
      need((input$onde %in% state.existe), "O estado escolhido não possui amostra suficiente.")
           )
        Rt.state <- resu5[[input$onde]] %>% left_join(resu15[[input$onde]],by="date") 
      }
    Rt.state 
  })
```


```{r , echo = FALSE }
output$table.R0 <- renderTable({
  
  
    if(input$checkbox){
      R0.state <- R0.est[[input$onde]]
    }else{
      R0.state <- R0[[input$onde]] 
    }
  
    tab.R0 <- R0.state%>% select(IC.i.r0, Est.r0 , IC.s.r0)
    names(tab.R0) <- c("Lim. Inf. 95%","R0","Lim. Sup. 95%")
    tab.R0
  },striped = TRUE)

```

Column {data-width=450}
-----------------------------------------------------------------------

### Número de Reprodução Instantâneo

```{r, echo = FALSE }
renderPlot({

plot1 <- ggplot(Rt.state(), aes(x = date)) +
  geom_line(aes(y = Est.5, color = "5 dias"), size = 0.8) + 
  geom_line(aes(y = Est.15, color = "15 dias"), size = 0.8) + 
  geom_ribbon(mapping = aes(x = date, 
                                   ymax = IC.s.5, ymin = IC.i.5),
              alpha = 0.5, fill = "brown1") +
  geom_ribbon(mapping = aes(x = date, 
                            ymax = IC.s.15, ymin = IC.i.15),
              alpha = 0.5, fill = "royalblue") +
  theme_classic() + 
  labs(title = paste("Número de Reprodução Instantâneo -",input$onde,"(5 e 15 dias)"),
       x = "Data",
       y = expression(R[t]),
       color="Janela Rolante:"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5),
    #plot.subtitle = element_text(hjust = 0.5),
    plot.caption = element_text(hjust = 0),
    axis.text.x=element_text(angle=75, hjust=1)
  ) +
  scale_x_date(date_breaks = "2 day", date_labels =  "%d %b")+
  ylim(0,NA)+
  scale_color_manual(values = c("5 dias" = "red","15 dias" = "blue"))+
  geom_hline(yintercept=1,linetype = "dashed")
    

plot1
})
```
